.\" Please adjust this date whenever revising the manpage.
.TH PYBACKPACK 1 "January 7, 2010"
.SH NAME
pybackpack \- File backup tool for GTK+
.SH SYNOPSIS
.B pybackpack
runs the pybackpack graphical interface which allows you to make 
backups of your files.
.SH DESCRIPTION
This manual page documents briefly the
.B pybackpack
command.
.PP
.B pybackpack
is a graphical file backup tool which allows you to easily make backups
of your files and save them to disk or burn them to a CD. It also allows
you to backup your files to a remote site using SSH.
.SH OPTIONS
None.
.SH AUTHOR
Pybackpack is maintained by Andrew Price and was originally written by Dave Arter.
.PP
This manual page was written by Andrew Price <andy@andrewprice.me.uk>

